### ISSUE TITLE
Adding Hebrew Language

### ISSUE THREAD

**Issue by lubani** [miso-belica/sumy#150]
hello, I tried to add the Hebrew language. I found hebrew tokenizer and added a null stemmer for hebrew (though I did find a hebrew stemmer too).
It doesn't print out anything if i try setting the language to hebrew (I included a sumy_example.py file)
Here is the Hebrew Tokenizer: https://github.com/YontiLevin/Hebrew-Tokenizer
Here is another Hebrew tokenizer: https://github.com/ygurman/hebrew_tokenizer
Here is a Hebrew stemmer: https://github.com/dannykh/hebrew_stemmer

I will include all the source code I changed.
Thanks in advance.
[sumy-master1.tar.gz](https://github.com/miso-belica/sumy/files/5207611/sumy-master1.tar.gz)

**Comment by miso-belica** [comment]
Hi @lubani can you please send me a pull request instead of gzip archive? It is much more effective to review your changes here at GitHub. I am sorry, but I am not in the mood to check the archive and hunt for changes there.

But I checked your sumy_example.py and it seems just a simple copy-paste from the README so it should work. I think the problem will be somewhere in the implementation of the other parts fro the Hebrew language.

**Comment by lubani** [comment]
I'm currently working on making it work.
I will send you a pull request when I will be done.
Thanks for your help

**Comment by lubani** [comment]
I made my Hebrew Summarizer and created a repository on Github:
https://github.com/lubani/HebrewSumy
