### ISSUE TITLE
LexRankSummarizer Bug(s)?

### ISSUE THREAD

**Issue by mponza** [miso-belica/sumy#22]
Hi, Miso Belica! :) I was running Sumy with the LexRank summarizer and I saw that the power_method always ends after one iteration. I think there is a bug: if you update p_vector with next_p before computing the new lambda_val, than the power_method ends after one iteration (in this way lambda_val is always zero after the first iteration).

In addition, I tried to see the values of the scores variable in the __call__ function. These values are usually very few despite the document have a lot of sentences (maybe there is another bug but I am not sure of this).

I found your project very useful! Thank you! :)

Marco

**Comment by miso-belica** [comment]
Thanks for this one. I'll dig into the lex-rank method deeper because another person noticed it does not work as expected. IMO is the right time to read the paper about this method again and check the implementation.

Good to here my little project is useful for someone. May I ask where and what for are you using sumy?

**Comment by mponza** [comment]
Thanks for the answer! I was using Sumy in order to compare same summarization algorithms :)

**Comment by miso-belica** [comment]
Hi, this should be now resolved. I [updated power method](https://github.com/miso-belica/sumy/blob/d9d8d27987735d8068b626e32aa78f337e6811bb/sumy/summarizers/lex_rank.py#L143-L145) so it uses algorithms from numpy instead of reinventing the whell. Thanks :)

If you think this issue is not resolved, please let me know. I plan to release new version of sumy this week.
