### ISSUE TITLE
Add numpy as a dependency

### ISSUE THREAD

**Issue by mkurnikov** [miso-belica/sumy#48]
In the `lsa.py`: 
```python
try:
    import numpy
except ImportError:
    numpy = None

try:
    from numpy.linalg import svd as singular_value_decomposition
except ImportError:
    singular_value_decomposition = None
```

and somewhere below this dependency is checked on `__call__` of the summarizer. 

I understand that in this case one doesn't have to install numpy if he isn't interested in numpy-based summarizers. But most python distributions people are using have numpy already installed anyway. 
Why won't just add numpy as a dependency? Then we can remove that `_ensure_dependencies_installed()` thing at all. 

Also, it could remove some tests like `test_numpy_not_installed` which essentially are testing python itself. 

I could add pull request for it, if you want.

**Comment by miso-belica** [comment]
Hi, numpy is added as dependency. You can install it by `pip install "sumy[LSA]"` I added numpy as optional dependency because it has binary dependencies and is not so easy to install it on Windows for beginners.

**Comment by mkurnikov** [comment]
Then, can I replace 
```python
try:
    import numpy
except ImportError:
    numpy = None

try:
    from numpy.linalg import svd as singular_value_decomposition
except ImportError:
    singular_value_decomposition = None
```

with
```python
try:
    import numpy as np
except ImportError as e:
    raise ImportError("LSA summarizer requires NumPy. Please, install it by command 'pip install numpy'.")
```
? 

Second one will break at `import LsaSummarizer` as first one will break on the `__call__`. It doesn't really matter, where it's going to break, but will make code much cleaner.

**Comment by mkurnikov** [comment]
Ok, it does matter, there is an import in `__main__.py`, so program won't start at all.

**Comment by miso-belica** [comment]
Your solution breaks installation. That's why it's in method call. I really don't want to force users not interested in LSA/LexRank to install some binary dependencies. If your package depends on LSA/LexRank you can add it as `sumy[LexRank]`.

This is really the best solution I found. Maybe I can add it into README and emit warning during installation process, but that's all.

Also I don't think this is true *But most python distributions people are using have numpy already installed anyway.*. I like the clean code much, but users are always more important than clean code.
